@host=https://localhost:7179

POST {{host}}/auth/register
Content-Type: application/json;

{
    "firstName":"Bruce",
    "lastName":" Iron",
    "email":"bruce.iron@emailreq.com",
    "password":"Pass123"
}